# Generated by Django 5.1.2 on 2025-01-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_fag_topic_fag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fag',
            name='laerer',
        ),
    ]
