# Generated by Django 5.1.2 on 2025-01-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_fag_laerer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='fag',
        ),
    ]
